# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
import pandas as pd
import sqlite3

from traitlets import This

my_form = sqlite3.connect('registration.sql')
cur = my_form.cursor()






class Ui_Form_l(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1311, 851)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 2, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.userIdLabel = QtWidgets.QLabel(Form)
        self.userIdLabel.setObjectName("userIdLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.userIdLabel)
        self.userIdLineEdit = QtWidgets.QLineEdit(Form)
        self.userIdLineEdit.setObjectName("userIdLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.userIdLineEdit)
        self.passwordLabel = QtWidgets.QLabel(Form)
        self.passwordLabel.setObjectName("passwordLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.passwordLabel)
        self.passwordLineEdit = QtWidgets.QLineEdit(Form)
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.passwordLineEdit)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout.setItem(0, QtWidgets.QFormLayout.SpanningRole, spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout.setItem(2, QtWidgets.QFormLayout.SpanningRole, spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout.setItem(4, QtWidgets.QFormLayout.SpanningRole, spacerItem2)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setObjectName("pushButton")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.SpanningRole, self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setObjectName("pushButton_2")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.SpanningRole, self.pushButton_2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout.setItem(6, QtWidgets.QFormLayout.SpanningRole, spacerItem3)
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setObjectName("pushButton_3")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.SpanningRole, self.pushButton_3)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout.setItem(8, QtWidgets.QFormLayout.SpanningRole, spacerItem4)
        self.verticalLayout.addLayout(self.formLayout)
        self.gridLayout.addLayout(self.verticalLayout, 2, 2, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 0, 2, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 1, 3, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem7, 1, 1, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem8, 1, 0, 2, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem9, 5, 2, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem10, 4, 2, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem11, 3, 2, 1, 1)

        self.retranslateUi(Form)
        self.pushButton_2.clicked.connect(self.passwordLineEdit.clear) # type: ignore
        self.pushButton_2.clicked.connect(self.userIdLineEdit.clear) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

        self.pushButton_3.clicked.connect(self.new)

        self.pushButton.clicked.connect(self.login) # type: ignore

   
 

    def login(self):
        sql = "SELECT userid FROM form"
        cur.execute(sql)
        userid = cur.fetchall()

        sql1="SELECT password FROM form"
        cur.execute(sql1)
        password=cur.fetchall()
        df=pd.DataFrame(userid)
        df1=pd.DataFrame(password)
        

        if self.userIdLineEdit.text() in df.values and self.passwordLineEdit.text() in df1.values:
            import mainwindows 
            
            self.window=QtWidgets.QMainWindow()
            self.ui=mainwindows.Ui_MainWindow()
            self.ui.setupUi(self.window)
            # Form.hide()
            self.window.show()
            
            
            print("you are logged in the page successfully")
            
            
            

        elif (self.userIdLineEdit.text() == ""
            or self.passwordLineEdit.text() == ""
            ):
            print("fill the values")

            msg = QMessageBox()
            msg.setWindowTitle("Error in the Form")
            msg.setText("please fill all the boxess")
            # msg.setIcon(self,QMessageBox.warning)

            msg.exec_()

        else:
            msg = QMessageBox()
            msg.setWindowTitle("Error in the Form")
            msg.setText("put valueable input")
            # msg.setIcon(self,QMessageBox.warning)

            msg.exec_()

       

    def new(self):
        from form import Ui_Form
        
        self.window=QtWidgets.QWidget()
        self.ui=Ui_Form()
        self.ui.setupUi(self.window)
        # self.hide() #for hide the current window this function is not working
        self.window.show()
        
        
        
        
        


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lineEdit.setText(_translate("Form", " DEVELOPERS LOG IN"))
        self.userIdLabel.setText(_translate("Form", "User Id"))
        self.passwordLabel.setText(_translate("Form", "Password"))
        self.pushButton.setText(_translate("Form", "Log In"))
        self.pushButton_2.setText(_translate("Form", "Reset"))
        self.pushButton_3.setText(_translate("Form", "New Registration"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form_l()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
